apiVersion: v1

kind: Pod

metadata:
        name: test-api
        labels:
                app: test-api

spec:
        containers:
                - name: test-api
                  image: gabrielkirsten/test-api
