apiVersion: v1

kind: Service

metadata:
        name: test-api-service

spec:
        type: NodePort
        ports:
                - targetPort: 8081
                  port: 8081
                  nodePort: 30080

        selector: 
                app: test-api
